In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from collections import Counter

pd.options.display.max_columns = None

In [3]:
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv'
url2 = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv'
df_usconf = pd.read_csv(url,error_bad_lines = False)
df_usdead = pd.read_csv(url2,error_bad_lines = False)

df_counties = pd.read_csv(r'X:\AC\Documents\Datasets\US Census and OMB Data\2020 Counties UID State CBSA CSA.csv', delimiter = ',', encoding = "ISO-8859-1")
df_counties = df_counties[['UID', 'CBSA Code', 'CBSA Title', 'CSA Code', 'CSA Title']]

In [4]:
#Add CBSA/CSA titles and codes to df
df_usconf = df_usconf.merge(df_counties, on = 'UID', how = 'left', suffixes=(False,False))
df_usconf = df_usconf.merge(df_usdead[['UID','Population']], on = 'UID', how = 'left', suffixes=(False,False))
cols = df_usconf.columns.tolist()
df_usconf = df_usconf[cols[0:1] + cols[4:6] + cols[8:10] + cols[-1:] + cols[6:8] + cols[-5:-1] + cols[11:-5]]

#convert date columns into a single column
df_usconf_pivot = df_usconf.melt(id_vars = df_usconf.columns[:12], var_name = 'Date', value_name = 'Total Confirmed Cases').sort_values(by = ['UID','Date']).reset_index(drop=True)
df_usdead_pivot = df_usdead.melt(id_vars = df_usdead.columns[:12], var_name = 'Date', value_name = 'Total Dead').sort_values(by = ['UID','Date']).reset_index(drop=True)

#df for daily increments
df_usconf_daily = df_usconf.copy()
df_usdead_daily = df_usdead.copy()
df_usconf_daily.iloc[:,12:] = df_usconf_daily.iloc[:,12:].diff(axis=1).fillna(0).astype('int')
df_usdead_daily.iloc[:,12:] = df_usdead_daily.iloc[:,12:].diff(axis=1).fillna(0).astype('int')

#convert date columns into a single column
df_usconf_daily = df_usconf_daily.melt(id_vars = df_usconf_daily.columns[:12], var_name = 'Date', value_name = 'Daily Confirmed Cases').sort_values(by = ['UID','Date']).reset_index(drop=True)
df_usdead_daily = df_usdead_daily.melt(id_vars = df_usdead_daily.columns[:12], var_name = 'Date', value_name = 'Daily Dead').sort_values(by = ['UID','Date']).reset_index(drop=True)

In [5]:
us_totals = df_usconf_pivot.merge(df_usdead_pivot[['UID','Date','Total Dead']], on = ['UID','Date'], how = 'left', suffixes = (False, False))
us_totals['Date'] = pd.to_datetime(us_totals['Date']).apply(lambda x: pd.datetime.strftime(x, '%m/%d/%y'))
us_totals = us_totals.sort_values(by = ['UID','Date']).reset_index(drop=True)

us_daily = df_usconf_daily.merge(df_usdead_daily[['UID','Date','Daily Dead']], on = ['UID','Date'], how = 'left', suffixes = (False, False))
us_daily['Date'] = pd.to_datetime(us_daily['Date']).apply(lambda x: pd.datetime.strftime(x, '%m/%d/%y'))
us_daily = us_daily.sort_values(by = ['UID','Date']).reset_index(drop=True)

In [6]:
statedaily = us_daily.loc[~us_daily['Province_State'].isin(['Diamond Princess','Grand Princess'])].groupby(['Province_State','Date'], as_index=False)['Population','Daily Confirmed Cases'].sum()
statedaily = statedaily.sort_values(['Date','Province_State'], ascending = [False,True]).reset_index(drop=True)
statecumsum = us_totals.groupby(['Province_State','Date'], as_index=False)['Total Confirmed Cases','Total Dead'].sum()
stategrp = pd.merge(statedaily, statecumsum, on = ['Province_State','Date'], how = 'left', suffixes = (False, False))

In [7]:
#Feature creation, rankings
stategrp['Total Cases per 1000 capita'] = stategrp['Total Confirmed Cases']/stategrp['Population']*1000

ranks = []
for date in stategrp['Date'].unique():
    for ranking in stategrp.copy().loc[stategrp['Date']==date,'Total Confirmed Cases'].rank(ascending = False, method='min'):
        ranks.append(ranking)
rankings = pd.DataFrame({'Total Cases Daily Ranking': ranks})
stategrp = pd.concat([stategrp, rankings], axis=1)

dates = stategrp['Date'].unique().tolist()
ustemp = pd.DataFrame()
for state in stategrp['Province_State'].unique():
    statetemp = stategrp.loc[stategrp['Province_State']==state].copy().reset_index(drop=True)
    yest = pd.Series(statetemp.loc[statetemp['Date'].isin(dates[1:]),'Total Cases Daily Ranking'].reset_index(drop=True)).rename('Total Cases Ranking Daily Change')
    statetemp = pd.concat([statetemp,yest], axis=1)
    ustemp = pd.concat([ustemp, statetemp])

stategrp = ustemp.sort_values(['Date','Total Cases Daily Ranking'], ascending = [False,True]).reset_index(drop=True)
stategrp['Total Cases Ranking Daily Change'] = stategrp['Total Cases Ranking Daily Change'] - stategrp['Total Cases Daily Ranking']

ranks = []
for date in stategrp['Date'].unique():
    for ranking in stategrp.copy().loc[stategrp['Date']==date,'Daily Confirmed Cases'].rank(ascending = False, method='min'):
        ranks.append(ranking)
rankings = pd.DataFrame({'Daily Cases Ranking': ranks})
stategrp = pd.concat([stategrp, rankings], axis=1)

ranks = []
for date in stategrp['Date'].unique():
    for ranking in stategrp.copy().loc[stategrp['Date']==date,'Total Cases per 1000 capita'].rank(ascending = False, method='min'):
        ranks.append(ranking)
rankings = pd.DataFrame({'Cases per Capita Ranking': ranks})
stategrp = pd.concat([stategrp, rankings], axis=1)

In [8]:
conf_total = us_daily['Daily Confirmed Cases'].sum()
conf_dead = us_daily['Daily Dead'].sum()
US_pop = 329943320 #as of 1/1/20


print('US Stats As of: ', us_totals['Date'].sort_values(ascending = True).to_list()[-1])
print('Total Confirmed Cases To Date: ', conf_total)
print('Confirmed Cases Percentage of US population: %.2f' %((conf_total/ US_pop) * 100),'%')
print('\n')
print('Total Deaths To Date: ', (conf_dead))
print('Confirmed Cases Percentage of US population: %.2f' %((conf_dead/ US_pop) * 100),'%')
print('Percentage of deaths from confirmed cases : %.2f' %((conf_dead/ US_pop)/(conf_total/ US_pop)*100),'%')
print('\n')

US Stats As of:  08/05/20
Total Confirmed Cases To Date:  4823889
Confirmed Cases Percentage of US population: 1.46 %


Total Deaths To Date:  158854
Confirmed Cases Percentage of US population: 0.05 %
Percentage of deaths from confirmed cases : 3.29 %

In [9]:
last14 = us_daily['Date'].values.tolist()[-14:]
prev2weekavg = us_daily.loc[(us_daily['Date'].isin(us_daily['Date'].values.tolist()[-15:-1]))].groupby('Date')['Daily Confirmed Cases'].sum().mean()
yestsum = us_daily.loc[(us_daily['Date']==us_daily['Date'].unique()[-1])]['Daily Confirmed Cases'].sum()

print('For Yesterday ({}):'.format(us_daily['Date'].unique()[-1]))
print('Increase in Total Confirmed Cases: ', yestsum)
print('Percentage increase from average of last two weeks: ', ((yestsum - prev2weekavg)/prev2weekavg * 100), '%')
print('\n')
print('Last 14 days:')
print('Total Confirmed Cases: ', us_daily.loc[(us_daily['Date'].isin(last14))]['Daily Confirmed Cases'].sum())
print('Average Cases per day: %.1f' %prev2weekavg)
print('Cases in Last 14 days as Percentage of Total Cases: %.2f' %((us_daily.loc[(us_daily['Date'].isin(last14))]['Daily Confirmed Cases'].sum()/(conf_total))*100),'%')

For Yesterday (08/05/20):
Increase in Total Confirmed Cases:  52810
Percentage increase from average of last two weeks:  -15.200563387389623 %


Last 14 days:
Total Confirmed Cases:  853769
Average Cases per day: 62276.4
Cases in Last 14 days as Percentage of Total Cases: 17.70 %

In [11]:
us_daily.to_csv(r'X:\AC\Documents\Datasets\US_daily_pivot.csv')
us_totals.to_csv(r'X:\AC\Documents\Datasets\US_totals_pivot.csv')

# Data Exploration

In [14]:
stategrp[0:9]

,Province_State,Date,Population,Daily Confirmed Cases,Total Confirmed Cases,Total Dead,Total Cases per 1000 capita,Total Cases Daily Ranking,Total Cases Ranking Daily Change,Daily Cases Ranking,Cases per Capita Ranking
0,California,08/03/20,39512223,4676,516851,9441,13.080788,1.0,0.0,3.0,23.0
1,Florida,08/03/20,21477737,4752,491884,7157,22.902040,2.0,0.0,2.0,3.0
2,Texas,08/03/20,28995881,8479,456624,7016,15.747892,3.0,0.0,1.0,15.0
3,New York,08/03/20,26161672,545,416843,32719,15.933347,4.0,0.0,25.0,14.0
4,Georgia,08/03/20,10617423,2258,195435,3842,18.407009,5.0,0.0,5.0,7.0
5,Illinois,08/03/20,12671821,1298,184522,7723,14.561601,6.0,0.0,7.0,19.0
6,New Jersey,08/03/20,8882190,264,182614,15846,20.559569,7.0,0.0,33.0,4.0
7,Arizona,08/03/20,7278717,1030,179497,3779,24.660527,8.0,0.0,11.0,2.0
8,North Carolina,08/03/20,10488084,2300,127630,2043,12.169048,9.0,0.0,4.0,25.0

In [15]:
#Top daily increases by state
stategrp.sort_values(by='Daily Confirmed Cases', ascending = False)[0:9]

,Province_State,Date,Population,Daily Confirmed Cases,Total Confirmed Cases,Total Dead,Total Cases per 1000 capita,Total Cases Daily Ranking,Total Cases Ranking Daily Change,Daily Cases Ranking,Cases per Capita Ranking
1234,Florida,07/12/20,21477737,15300,269811,4242,12.562357,3.0,0.0,1.0,10.0
1011,Texas,07/16/20,28995881,14962,305854,3657,10.548188,4.0,0.0,1.0,19.0
280,California,07/29/20,39512223,14151,484913,8908,12.272481,1.0,0.0,1.0,23.0
1010,Florida,07/16/20,21477737,13965,315775,4677,14.702434,3.0,0.0,2.0,8.0
1513,California,07/07/20,39512223,12977,284012,6573,7.187953,2.0,0.0,1.0,30.0
1121,California,07/14/20,39512223,12854,346211,7250,8.762124,2.0,0.0,1.0,24.0
336,California,07/28/20,39512223,12641,470762,8679,11.914339,1.0,0.0,1.0,24.0
1178,Florida,07/13/20,21477737,12624,282435,4277,13.150128,3.0,0.0,1.0,10.0
675,Texas,07/22/20,28995881,12544,363615,4453,12.540229,4.0,0.0,1.0,19.0

In [17]:
#top daily increases of cases per capita
stategrp.assign(x = stategrp['Daily Confirmed Cases']/stategrp['Population']).sort_values(by='x', ascending = False).drop('x',axis=1)[0:9]

,Province_State,Date,Population,Daily Confirmed Cases,Total Confirmed Cases,Total Dead,Total Cases per 1000 capita,Total Cases Daily Ranking,Total Cases Ranking Daily Change,Daily Cases Ranking,Cases per Capita Ranking
459,Louisiana,07/26/20,4648794,3840,107574,3763,23.140195,12.0,0.0,3.0,1.0
65,Louisiana,08/02/20,4648794,3467,119747,4007,25.758724,10.0,2.0,3.0,1.0
5658,Massachusetts,04/24/20,6892503,4973,51700,2556,7.500904,3.0,0.0,2.0,3.0
1234,Florida,07/12/20,21477737,15300,269811,4242,12.562357,3.0,0.0,1.0,10.0
795,Louisiana,07/20/20,4648794,3186,94892,3574,20.412176,12.0,0.0,4.0,1.0
851,Louisiana,07/19/20,4648794,3116,91706,3543,19.726837,12.0,0.0,5.0,3.0
1857,Arizona,07/01/20,7278717,4877,84105,1725,11.554921,10.0,0.0,4.0,9.0
1010,Florida,07/16/20,21477737,13965,315775,4677,14.702434,3.0,0.0,2.0,8.0
1913,Arizona,06/30/20,7278717,4683,79228,1645,10.884885,10.0,0.0,4.0,11.0

In [18]:
#Top daily increases by county
us_daily.sort_values(by=['Daily Confirmed Cases'], ascending = False)[['Admin2','Province_State','Date','Daily Confirmed Cases','Daily Dead']][0:5]

,Admin2,Province_State,Date,Daily Confirmed Cases,Daily Dead
378774,New York,New York,04/15/20,7837,561
56325,Los Angeles,California,07/05/20,7198,30
378763,New York,New York,04/04/20,6147,696
511271,Bexar,Texas,07/16/20,5980,28
378770,New York,New York,04/11/20,5924,714

# CA Data Exploration

In [19]:
us_daily.loc[(us_daily['Province_State']=='California')&(us_daily['Admin2']=='San Francisco'),['Date','Daily Confirmed Cases']].tail()

           Date  Daily Confirmed Cases
60055  07/30/20                    226
60056  07/31/20                    152
60057  08/01/20                    148
60058  08/02/20                     88
60059  08/03/20                    105

In [21]:
#Top daily increases for CA
stategrp.loc[stategrp['Province_State']=='California'].sort_values(by=['Daily Confirmed Cases'], ascending = False)[0:4]

,Province_State,Date,Population,Daily Confirmed Cases,Total Confirmed Cases,Total Dead,Total Cases per 1000 capita,Total Cases Daily Ranking,Total Cases Ranking Daily Change,Daily Cases Ranking,Cases per Capita Ranking
280,California,07/29/20,39512223,14151,484913,8908,12.272481,1.0,0.0,1.0,23.0
1513,California,07/07/20,39512223,12977,284012,6573,7.187953,2.0,0.0,1.0,30.0
1121,California,07/14/20,39512223,12854,346211,7250,8.762124,2.0,0.0,1.0,24.0
336,California,07/28/20,39512223,12641,470762,8679,11.914339,1.0,0.0,1.0,24.0

In [22]:
#Create df for CA's CBSAs
cacbsa_daily = us_daily.loc[(us_daily['Province_State']=='California')].groupby(['Province_State','CBSA Title','Date'], as_index=False)['Population','Daily Confirmed Cases'].sum()
cacbsa_daily = cacbsa_daily.sort_values(['Date','Daily Confirmed Cases'], ascending = [False,False]).reset_index(drop=True)
cacbsa_cumsum = us_totals.loc[us_totals['Province_State']=='California'].groupby(['Province_State','CBSA Title','Date'], as_index=False)['Total Confirmed Cases','Total Dead'].sum()
cacbsa = pd.merge(cacbsa_daily, cacbsa_cumsum, on = ['Province_State','CBSA Title','Date'], how = 'left', suffixes = (False, False))

In [23]:
#Feature creation, rankings
cacbsa['Total Cases per 1000 capita'] = cacbsa['Total Confirmed Cases']/cacbsa['Population']*1000

ranks = []
for date in cacbsa['Date'].unique():
    for ranking in cacbsa.copy().loc[cacbsa['Date']==date,'Total Confirmed Cases'].rank(ascending = False, method='min'):
        ranks.append(ranking)
rankings = pd.DataFrame({'Total Cases Daily Ranking': ranks})
cacbsa = pd.concat([cacbsa, rankings], axis=1)

dates = cacbsa['Date'].unique().tolist()
cacbsatemp = pd.DataFrame()
for state in cacbsa['CBSA Title'].unique():
    cbsatemp = cacbsa.loc[cacbsa['CBSA Title']==state].copy().reset_index(drop=True)
    yest = pd.Series(cbsatemp.loc[cbsatemp['Date'].isin(dates[1:]),'Total Cases Daily Ranking'].reset_index(drop=True)).rename('Total Cases Ranking Daily Change')
    cbsatemp = pd.concat([cbsatemp,yest], axis=1)
    cacbsatemp = pd.concat([cacbsatemp, cbsatemp])
    
cacbsa = cacbsatemp.sort_values(['Date','Total Cases Daily Ranking'], ascending = [False,True]).reset_index(drop=True)
cacbsa['Total Cases Ranking Daily Change'] = cacbsa['Total Cases Ranking Daily Change'] - cacbsa['Total Cases Daily Ranking']

In [24]:
cacbsa.loc[(cacbsa['CBSA Title']=='Los Angeles-Long Beach-Anaheim, CA')]

,Province_State,CBSA Title,Date,Population,Daily Confirmed Cases,Total Confirmed Cases,Total Dead,Total Cases per 1000 capita,Total Cases Daily Ranking,Total Cases Ranking Daily Change
0,California,"Los Angeles-Long Beach-Anaheim, CA",08/03/20,13214799,2122,231690,5353,17.532616,1.0,0.0
34,California,"Los Angeles-Long Beach-Anaheim, CA",08/02/20,13214799,1878,229568,5344,17.372039,1.0,0.0
68,California,"Los Angeles-Long Beach-Anaheim, CA",08/01/20,13214799,2953,227690,5318,17.229925,1.0,0.0
102,California,"Los Angeles-Long Beach-Anaheim, CA",07/31/20,13214799,2923,224737,5242,17.006464,1.0,0.0
136,California,"Los Angeles-Long Beach-Anaheim, CA",07/30/20,13214799,3086,221814,5163,16.785272,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
6460,California,"Los Angeles-Long Beach-Anaheim, CA",01/26/20,13214799,2,2,0,0.000151,1.0,0.0
6494,California,"Los Angeles-Long Beach-Anaheim, CA",01/25/20,13214799,0,0,0,0.000000,1.0,0.0
6528,California,"Los Angeles-Long Beach-Anaheim, CA",01/24/20,13214799,0,0,0,0.000000,1.0,0.0
6562,California,"Los Angeles-Long Beach-Anaheim, CA",01/23/20,13214799,0,0,0,0.000000,1.0,0.0
6596,California,"Los Angeles-Long Beach-Anaheim, CA",01/22/20,13214799,0,0,0,0.000000,1.0,NaN

In [25]:
cacbsa.loc[cacbsa['Date']==cacbsa['Date'][0]]

,Province_State,CBSA Title,Date,Population,Daily Confirmed Cases,Total Confirmed Cases,Total Dead,Total Cases per 1000 capita,Total Cases Daily Ranking,Total Cases Ranking Daily Change
0,California,"Los Angeles-Long Beach-Anaheim, CA",08/03/20,13214799,2122,231690,5353,17.532616,1.0,0.0
1,California,"Riverside-San Bernardino-Ontario, CA",08/03/20,4650631,452,70443,1113,15.146977,2.0,0.0
2,California,"San Francisco-Oakland-Berkeley, CA",08/03/20,4731803,409,37248,566,7.871841,3.0,0.0
3,California,"San Diego-Chula Vista-Carlsbad, CA",08/03/20,3338330,0,29883,565,8.951482,4.0,0.0
4,California,"Bakersfield, CA",08/03/20,900202,106,20651,144,22.940407,5.0,0.0
5,California,"Fresno, CA",08/03/20,999101,0,15083,138,15.096572,6.0,0.0
6,California,"Sacramento-Roseville-Folsom, CA",08/03/20,2363730,83,14256,204,6.031146,7.0,0.0
7,California,"Stockton, CA",08/03/20,762148,402,11885,180,15.594084,8.0,0.0
8,California,"San Jose-Sunnyvale-Santa Clara, CA",08/03/20,1990660,172,11441,195,5.747340,9.0,0.0
9,California,"Visalia, CA",08/03/20,466195,291,9745,189,20.903270,10.0,0.0
10,California,"El Centro, CA",08/03/20,181215,39,9448,222,52.136964,11.0,0.0
11,California,"Modesto, CA",08/03/20,550660,160,9221,112,16.745360,12.0,0.0
12,California,"Oxnard-Thousand Oaks-Ventura, CA",08/03/20,846006,0,7344,76,8.680789,13.0,0.0
13,California,"Santa Maria-Santa Barbara, CA",08/03/20,446499,0,6167,60,13.811901,14.0,0.0
14,California,"Salinas, CA",08/03/20,434061,102,4924,30,11.344028,15.0,0.0
15,California,"Hanford-Corcoran, CA",08/03/20,152940,73,4453,56,29.115993,16.0,0.0
16,California,"Merced, CA",08/03/20,277680,0,4285,50,15.431432,17.0,0.0
17,California,"Vallejo, CA",08/03/20,447643,0,3611,37,8.066696,18.0,0.0
18,California,"Santa Rosa-Petaluma, CA",08/03/20,494336,58,3113,39,6.297336,19.0,0.0
19,California,"Madera, CA",08/03/20,157327,0,1943,30,12.350073,20.0,0.0
20,California,"San Luis Obispo-Paso Robles, CA",08/03/20,283111,119,1902,16,6.718213,21.0,0.0
21,California,"Yuba City, CA",08/03/20,175639,28,1299,10,7.395852,22.0,0.0
22,California,"Santa Cruz-Watsonville, CA",08/03/20,273213,0,1152,4,4.216490,23.0,0.0
23,California,"Chico, CA",08/03/20,219186,0,941,7,4.293157,24.0,0.0
24,California,"Napa, CA",08/03/20,137744,0,888,8,6.446742,25.0,0.0
25,California,"Susanville, CA",08/03/20,30573,-5,626,0,20.475583,26.0,0.0
26,California,"Redding, CA",08/03/20,180080,21,390,9,2.165704,27.0,0.0
27,California,"Ukiah, CA",08/03/20,86749,5,322,9,3.711858,28.0,0.0
28,California,"Truckee-Grass Valley, CA",08/03/20,99755,0,299,1,2.997343,29.0,0.0
29,California,"Red Bluff, CA",08/03/20,65084,0,234,1,3.595354,30.0,0.0
30,California,"Eureka-Arcata, CA",08/03/20,135558,0,233,4,1.718821,31.0,0.0
31,California,"Clearlake, CA",08/03/20,64386,13,208,1,3.230516,32.0,0.0
32,California,"Sonora, CA",08/03/20,54478,0,141,2,2.588201,33.0,0.0
33,California,"Crescent City, CA",08/03/20,27812,0,88,0,3.164102,34.0,0.0

In [214]:
cacbsa.loc[cacbsa['CBSA Title']=='San Francisco-Oakland-Berkeley, CA'].describe()

,Population,Daily Confirmed Cases,Total Confirmed Cases,Total Dead,Total Cases per 1000 capita,Total Cases Daily Ranking,Total Cases Ranking Daily Change
count,190.0,190.000000,190.000000,190.000000,190.000000,190.000000,189.000000
mean,4731803.0,183.194737,7996.242105,174.757895,1.689893,2.889474,-0.010582
std,0.0,212.696443,9380.230627,169.899299,1.982380,0.983135,0.371733
min,4731803.0,0.000000,0.000000,0.000000,0.000000,1.000000,-2.000000
25%,4731803.0,6.500000,25.250000,0.000000,0.005336,2.000000,0.000000
50%,4731803.0,119.500000,4883.000000,152.500000,1.031953,3.000000,0.000000
75%,4731803.0,223.500000,12137.500000,311.500000,2.565090,3.000000,0.000000
max,4731803.0,875.000000,34807.000000,526.000000,7.355970,6.000000,3.000000

In [187]:
#Top daily increases in CA counties
us_daily.loc[us_daily['Province_State']=='California'].sort_values(by=['Daily Confirmed Cases'], ascending = False)[['Admin2','Province_State','Date','Daily Confirmed Cases','Daily Dead']][0:4]

            Admin2 Province_State      Date  Daily Confirmed Cases  Daily Dead
54885  Los Angeles     California  07/05/20                   7198          30
54909  Los Angeles     California  07/29/20                   4814          92
54896  Los Angeles     California  07/16/20                   4471          46
54894  Los Angeles     California  07/14/20                   4219          73

In [189]:
#counties on 7/29
us_daily.loc[(us_daily['Province_State']=='California') & (us_daily['Date']=='07/29/20'),['Admin2','Province_State','Date','Daily Confirmed Cases','Daily Dead']].sort_values(by='Daily Confirmed Cases', ascending=False)[0:4]

,Admin2,Province_State,Date,Daily Confirmed Cases,Daily Dead
54909,Los Angeles,California,07/29/20,4814,92
58139,San Bernardino,California,07/29/20,2347,24
57569,Riverside,California,07/29/20,972,11
58329,San Diego,California,07/29/20,780,19

In [1]:
us_daily.loc[(us_daily['Province_State']=='California') & (us_daily['Admin2']=='Alameda')]

SyntaxError: unexpected EOF while parsing (<ipython-input-1-793a51970eeb>, line 1)

# APPENDIX

In [ ]:
url3 = 'https://covidtracking.com/api/v1/states/daily.csv'
df_testing = pd.read_csv(url3,error_bad_lines = False)

df_testing = df_testing.rename(columns = {'date':'Date','state':'Province_State'})
df_testing[['totalTestResultsIncrease','positiveIncrease','negativeIncrease','totalTestResults','positive','negative']] = df_testing[['totalTestResultsIncrease','positiveIncrease','negativeIncrease','totalTestResults','positive','negative']].fillna(0)

to_fix = ['totalTestResultsIncrease','positiveIncrease','negativeIncrease']
actual = ['totalTestResults','positive','negative']
columns = df_testing.columns
def fill_func(states):
    for state in states:
        for col in range(0,len(to_fix)):
            cumsum = df_testing.loc[df_testing['Province_State']==state].sort_values(by='Date')[to_fix[col]].cumsum()
            actualsum = df_testing.loc[df_testing['Province_State']==state,['Date',actual[col]]].sort_values(by='Date')[actual[col]]
            comparison = cumsum.eq(actualsum)
            if comparison[comparison == False].count() > 0:
                Earliest_index = comparison[comparison == False].index[0]
                df_testing.iloc[Earliest_index,columns.get_loc(to_fix[col])] = df_testing.iloc[Earliest_index,columns.get_loc(actual[col])]
                
fill_func(df_testing['Province_State'].unique())
df_testing = df_testing.replace({'Province_State':states})
df_testing['Date'] = pd.to_datetime(df_testing['Date'], format='%Y%m%d').apply(lambda x: pd.datetime.strftime(x, '%m/%d/%y'))

In [ ]:
#missing CBSA codes after merge: 41980, 10380, 38660, 11640, 41900, 49500, 32420, 25020, 27580, 17620, 17640, 42180
#They're all in Puerto Rico. Span across multiple CBSA and CSA. Should just ignore
res = Counter(df_counties['CBSA Code'].value_counts().to_dict()) - Counter(df_usconf['CBSA Code'].value_counts().to_dict())
pd.set_option('display.max_rows', None)
df_counties[df_counties['CBSA Code'].isin(list(res.keys()))]

In [ ]:
df_usconf.loc[df_usconf['UID']==630,['CBSA Code', 'CBSA Title', 'CSA Code', 'CSA Title']] = [41980,'San Juan-Bayamón-Caguas, PR', 490.0, 'San Juan-Bayamón, PR']
df_usconf.loc[df_usconf['UID']==630][['CBSA Code', 'CBSA Title', 'CSA Code', 'CSA Title']]

In [ ]:
columns_to_remove = ['iso2', 'iso3', 'code3', 'Combined_Key']
df_usconf = df_usconf[Counter(df_usconf.columns.tolist()) - Counter(columns_to_remove)]
df_usdead = df_usdead[Counter(df_usdead.columns.tolist()) - Counter(columns_to_remove)]

In [ ]:
#Add additional column for CBSAs and CSAs before melting?

'''BA_counties = ['Alameda','Contra Costa','Marin','Napa','San Francisco','San Mateo','Santa Clara','Solano','Sonoma']
LA_counties =['Ventura','San Bernadio', 'Riverside', 'Los Angeles', 'Orange']'''

In [ ]:
#California and Texas total confirmed cases differ by 2000+. Stick to COVIDTESTING data for testing dataframe
totalgrp = us_totals.groupby(['Province_State','Date'], as_index=False)['Total Confirmed Cases','Total Dead'].sum()
comparison = df_testing.loc[df_testing['Date']=='07/27/20', ['Province_State','Date','positive']].merge(totalgrp.loc[totalgrp['Date']=='07/27/20',['Province_State','Date','Total Confirmed Cases']], on=['Province_State','Date'], how = 'left', suffixes = (False, False))
comparison['Delta'] = comparison['positive'] - comparison['Total Confirmed Cases']
comparison